[package]
name = "backup_app_rust"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
dirs = "3.0"
url = "2.1"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
anyhow = "1.0"
maplit = "1.0"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.6", features=["diesel_types"] }

[[bin]]
name = "backup-app-rust"
path = "src/main.rs"
doc = false
