[package]
name = "backup_app_rust"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
dirs = "3.0"
url = "2.1"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
anyhow = "1.0"
maplit = "1.0"
derive_more = "0.99"
lazy_static = "1.4"
structopt = "0.3"
chrono = {version="0.4", features=["serde"]}
regex = "1.3"
deadpool = "0.5"
deadpool-postgres = "0.5"
itertools = "0.9"
tar = "0.4"
flate2 = "1.0"
tokio = { version="0.2", features=["full"]}
log = "0.4"
tokio-postgres = {version = "0.5", features = ["with-chrono-0_4", "with-uuid-0_8"]}
env_logger = "0.7"
tempfile = "3.1"
rand = "0.7"
futures = "0.3"
rusoto_core = {version = "0.45", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.45", default_features = false, features=["rustls"]}
s3-ext = "0.1"
sts_profile_auth = "0.5"
parking_lot = "0.11"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.6", features=["diesel_types"] }

[[bin]]
name = "backup-app-rust"
path = "src/main.rs"
doc = false
