[package]
name = "backup_app_rust"
version = "0.2.9"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[package.metadata.deb]
name = "backup-app-rust"
priority = "optional"
section = "rust"
provides = "backup-app-rust"
extended-description = """\
Backup utility written in rust"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
dirs = "4.0"
url = "2.2"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
anyhow = "1.0"
maplit = "1.0"
derive_more = "0.99"
lazy_static = "1.4"
structopt = "0.3"
chrono = {version="0.4", features=["serde"]}
regex = "1.4"
deadqueue = "0.2"
itertools = "0.10"
flate2 = "1.0"
tokio = { version="1.2", features=["full"]}
log = "0.4"
env_logger = "0.9"
tempfile = "3.2"
rand = "0.8"
futures = "0.3"
rusoto_core = {version = "0.47", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.47", default_features = false, features=["rustls"]}
s3-ext = "0.4"
sts_profile_auth = "0.6"
parking_lot = "0.11"
num_cpus = "1.13"
rayon = "1.5"
stack-string = "0.5"

[[bin]]
name = "backup-app-rust"
path = "src/main.rs"
doc = false
